name: build

on:
  push:
    branches: [ master ]
    branches: [ ddx ]
  pull_request:
    branches: [ master ]
    branches: [ ddx ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2

    - name: Generate Submodules
      run: git submodule init

    - name: Update Submodules
      run: git submodule update

    - name: Generate Project Files
      run: scripts/WindowsGenProjects.bat

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Solution
      run: msbuild -property:Configuration=Debug,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo Saturn.sln
