name: CI(Linux)

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]
jobs:
  build:
    runs-on: ubuntu-latest
     permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Install X11
    - run: sudo apt install xorg-dev

    - name: Generate Submodules
      run: git submodule update --init

    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.1

    - name: Generate Project Files
      run: ./tpremake/premake5 gmake2

    - name: Make Solution
      run: make
