name: CI(Linux)

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Install X11
      run: sudo apt install libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglu1-mesa-dev

    - name: Generate Submodules
      run: git submodule update --init

    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.1

    - name: Generate Project Files
      run: ./tpremake/premake5 gmake2

    - name: Make Solution
      run: make -j
