name: CI(MacOS)

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]
jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Generate Submodules
      run: git submodule update --init

    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.1

    - name: Generate Project Files
      run: ./tpremake/premake5 xcode4

    - name: Clean project
      run: xcodebuild clean -workspace "Saturn.xcworkspace" -scheme "Saturn"

    - name: Build project
      run: xcodebuild build -workspace "Saturn.xcworkspace" -scheme "Saturn" -configuration Release | xcpretty -c && exit ${PIPESTATUS[0]}
