name: CI( Update )

# https://github.com/Geno-IDE/llvm/blob/master/.github/workflows/ci.yml#L4
on:
  schedule:
    # 00:00 on Mondays
  - cron: '00 00 * * 1'
  workflow_dispatch:
  
jobs:
    update_glm:
      name: Update GLM
      runs-on: windows-latest
      continue-on-error: true
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
            
        - name: Get Name
          id: date
          run: echo "::set-output name=date::$(Get-Date -Format "yyyy-MM-dd")"
        - name: Update Submodule
        
          run: |
           cd Saturn/vendor/glm
           git submodule update --remote --merge
           git add glm
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Actions"
           git commit -m "Latest glm as of ${{ steps.date.outputs.date }}"
           git push origin master
