name: CI(Windows)

on:
  push:
    branches: [ vulkan ]
  pull_request:
    branches: [ vulkan ]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.3
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Generate Project Files
      run: scripts/WindowsGenProjects-CI.bat

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build Solution
      run: msbuild -property:Configuration=Debug,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo Saturn.sln
